package com.smartwifi.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.smartwifi.bean.ShopDBBean;

import com.smartwifi.db.ShopDBBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopDBBeanDaoConfig;

    private final ShopDBBeanDao shopDBBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopDBBeanDaoConfig = daoConfigMap.get(ShopDBBeanDao.class).clone();
        shopDBBeanDaoConfig.initIdentityScope(type);

        shopDBBeanDao = new ShopDBBeanDao(shopDBBeanDaoConfig, this);

        registerDao(ShopDBBean.class, shopDBBeanDao);
    }
    
    public void clear() {
        shopDBBeanDaoConfig.clearIdentityScope();
    }

    public ShopDBBeanDao getShopDBBeanDao() {
        return shopDBBeanDao;
    }

}
